
      <!-- FOOTER -->
      <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2016 Vickie Chen. &middot; WEB Tools used: HTML, CSS,JS (jquery, Angular, Bootstrap,etc), JSON FILE</p>
      </footer>

    </div><!-- /.container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="js/jquery.min.js"><\/script>')</script>
    <script src="js/angular.min.js"></script>
    <script src="js/bootstrap.min.js"></script>		
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
	<script src="js/modal.js"></script>	
    <script src="js/holder.min.js"></script>
	<script src="js/app.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="js/ie10-viewport-bug-workaround.js"></script>
	
	</div><!-- /. ng-controller-->
  </body>
</html>
 
