 <hr>	
 <p class="pull-right" style="position:fixed;bottom:10px;right:10px"><a href="#">Back to top</a></p>
 
 <!-- FOOTER -->	
    <footer>
        <p>&copy; 2016 Vickie Chen. &middot; WEB Tools used: HTML, CSS, JS(jquery, Angular, Bootstrap,etc), JSON file.</p>
    </footer>

    </div><!-- Angular homeController Controller-->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="js/jquery.min.js"><\/script>')</script>
    <script src="js/angular.min.js"></script>
    <script src="js/bootstrap.min.js"></script>		
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
	<script src="js/modal.js"></script>	
    <script src="js/holder.min.js"></script>
	<script src="js/ie-emulation-modes-warning.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="js/ie10-viewport-bug-workaround.js"></script>
	<script src="http://maps.googleapis.com/maps/api/js"></script>		
	<script type="text/javascript" src="http://www.google.com/jsapi?key=###api-key###"></script>
	<script src="js/app.js"></script>
  </body>
</html>
 